<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240519103535 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE car (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vin VARCHAR(255) NOT NULL, state_number VARCHAR(15) DEFAULT NULL, payload VARCHAR(15) DEFAULT NULL, remaining_fuel VARCHAR(15) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE cargo_row (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, guid UUID DEFAULT NULL, qty VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, full_address TEXT DEFAULT NULL, inn VARCHAR(13) DEFAULT NULL, kpp VARCHAR(13) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, guid UUID DEFAULT NULL, corr_account VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE deal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id INT DEFAULT NULL, user_info_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E3FEC11619EB6921 ON deal (client_id)');
        $this->addSql('CREATE INDEX IDX_E3FEC116586DFF2 ON deal (user_info_id)');
        $this->addSql('CREATE TABLE deal_cargo_row (deal_id INT NOT NULL, cargo_row_id INT NOT NULL, PRIMARY KEY(deal_id, cargo_row_id))');
        $this->addSql('CREATE INDEX IDX_12E4DAE0F60E2305 ON deal_cargo_row (deal_id)');
        $this->addSql('CREATE INDEX IDX_12E4DAE091CB6BBF ON deal_cargo_row (cargo_row_id)');
        $this->addSql('CREATE TABLE note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT DEFAULT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CFBDFA147E3C61F9 ON note (owner_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('ALTER TABLE deal ADD CONSTRAINT FK_E3FEC11619EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deal ADD CONSTRAINT FK_E3FEC116586DFF2 FOREIGN KEY (user_info_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deal_cargo_row ADD CONSTRAINT FK_12E4DAE0F60E2305 FOREIGN KEY (deal_id) REFERENCES deal (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deal_cargo_row ADD CONSTRAINT FK_12E4DAE091CB6BBF FOREIGN KEY (cargo_row_id) REFERENCES cargo_row (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA147E3C61F9 FOREIGN KEY (owner_id) REFERENCES client (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deal DROP CONSTRAINT FK_E3FEC11619EB6921');
        $this->addSql('ALTER TABLE deal DROP CONSTRAINT FK_E3FEC116586DFF2');
        $this->addSql('ALTER TABLE deal_cargo_row DROP CONSTRAINT FK_12E4DAE0F60E2305');
        $this->addSql('ALTER TABLE deal_cargo_row DROP CONSTRAINT FK_12E4DAE091CB6BBF');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA147E3C61F9');
        $this->addSql('DROP TABLE car');
        $this->addSql('DROP TABLE cargo_row');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE deal');
        $this->addSql('DROP TABLE deal_cargo_row');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE "user"');
    }
}
